promtail_config_scrape_configs:
- job_name: apt
  static_configs:
    - targets:
        - localhost
      labels:
        job: apt
        host: "{{ ansible_fqdn }}"
        __path__: /var/log/apt/history.log
  pipeline_stages:
  - replace:
      expression: "^(\\d+-\\d+-\\d+ \\d+:\\d+:\\d+,\\d+ )"
  - pack:
      labels:

- job_name: syslog
  static_configs:
    - targets:
        - localhost
      labels:
        job: syslog
        host: "{{ ansible_fqdn }}"
        __path__: /var/log/syslog
  pipeline_stages:
  - replace:
      expression: "^(\\d+-\\d+-\\d+ \\d+:\\d+:\\d+,\\d+ )"
  - pack:
      labels: