all:
  hosts:
    loki-test:
      ansible_host: 100.105.6.8
    promtail-test:
      ansible_host: 100.105.6.9
    monolab-nextcloud:
      ansible_host: 100.105.6.6
    monolab-mx1:
      ansible_host: 100.105.6.4

loki:
  hosts:
    loki-test:

postgresql:
  hosts:
    monolab-mx1:

syslog:
  hosts:
    monolab-nextcloud:
    promtail-test:

promtail:
  children:
    postgresql:
    syslog:

     